name: flutter_ioc
description: A standard interface providing inversion of control services to Dart or Flutter applications.
version: 1.1.0

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  get_it: ^7.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
