name: flutter_ioc
description: A standard interface providing inversion of control services to Dart or Flutter applications.
repository: https://github.com/Baseflow/flutter_ioc/tree/main/packages/flutter_ioc
version: 2.2.0
topics: 
  - ioc

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.16.0
