name: flutter_ioc
description: A standard interface providing inversion of control services to Dart or Flutter applications.
repository: https://github.com/Baseflow/flutter_ioc/tree/main/packages/flutter_ioc
version: 2.1.0

environment:
  sdk: '>=2.18.1 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
