name: flutter_ioc_get_it
description: An implementation of the flutter_ioc package based on get_it.
repository: https://github.com/Baseflow/flutter_ioc/tree/main/packages/flutter_ioc_get_it
version: 1.2.1

environment:
  sdk: '>=2.18.1 <4.0.0'

dependencies:
  flutter_ioc: ^2.1.0
  get_it: ^7.6.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
