name: flutter_ioc_get_it
description: An implementation of the flutter_ioc package based on get_it.
repository: https://github.com/Baseflow/flutter_ioc/tree/main/packages/flutter_ioc_get_it
version: 1.3.0
topics: 
  - ioc
  - get_it

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_ioc: ^2.2.0
  get_it: ^7.7.0

dev_dependencies:
  flutter_lints: ^4.0.0
  test: ^1.16.0
