name: flutter_ioc_example
description: An example application demonstrating how to use the flutter_ioc package.
version: 1.0.0

publish_to: none

dependencies:
  flutter_ioc_get_it:
    path: ../../flutter_ioc_get_it

environment:
  sdk: '>=2.18.1 <3.0.0'