name: flutter_ioc_get_it

on:
  push:
    branches: [ main ]
    paths:
    - 'packages/flutter_ioc_get_it/**'
    - '.github/workflows/flutter_ioc_get_it.yaml'
  pull_request:
    branches: [ main ]
    paths:
    - 'packages/flutter_ioc_get_it/**'
    - '.github/workflows/flutter_ioc_get_it.yaml'

jobs:
  format:
    name: CI - Flutter IoC Get_It

    runs-on: ubuntu-latest

    env:
      source-directory: ./packages/flutter_ioc_get_it 

    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Download dependencies
        run: flutter pub get
        working-directory: ${{env.source-directory}}

      - name: Run Flutter Format
        run: dart format --set-exit-if-changed .
        working-directory: ${{env.source-directory}}
     
      - name: Run Flutter Analyzer
        run: flutter analyze
        working-directory: ${{env.source-directory}}

      #- name: Run unit tests
      #  run: flutter test
      #  working-directory: ${{env.source-directory}}
